options:
  logging: NONE

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/chat:$SHORT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/chat:$SHORT_SHA']
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['set', 'image', 'deployments.apps/chat', 'chat=gcr.io/$PROJECT_ID/chat:$SHORT_SHA']