steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'us-central1-docker.pkg.dev/k8s-project-387912/coen-chat', '-f', './', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/k8s-project-387912/coen-chat']
images: ['us-central1-docker.pkg.dev/k8s-project-387912/coen-chat']