options:
  logging: NONE

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'us-west4-docker.pkg.dev/k8s-project-387912/coen-chat/chat', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-west4-docker.pkg.dev/k8s-project-387912/coen-chat/chat']
images: ['us-west4-docker.pkg.dev/k8s-project-387912/coen-chat/chat']