name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  DEPLOYMENT_NAME: coen-chat-deployment

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMG_NAME: chat
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.IMG_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value={{sha}},enable=${{ github.ref_type != 'tag' }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ github.repository_owner }}/chat:latest
            ${{ github.repository_owner }}/${{ steps.metadata.outputs.tags }}

      - id: "auth"
        name: Authenticate to GCP
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_ACCESS_KEY }}

      - name: server-on
        run: |-
          gcloud compute ssh --zone "${{ secrets.GCP_INSTANCE_ZONE }}" "${{ secrets.GCP_INSTANCE }}" --project "${{ secrets.GCP_PROJECT }}" -- \
          "sudo kubectl set image deployments.apps/${{ env.DEPLOYMENT_NAME }} ${{ env.DEPLOYMENT_NAME }}=${{ github.repository_owner }}/${{ steps.metadata.outputs.tags }}"