name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/chat:${{ github.head_ref }}

      - id: "auth"
        name: Authenticate to GCP
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_ACCESS_KEY }}

      - name: server-on
        run: |-
          gcloud compute ssh --project=${{ secrets.GCP_PROJECT }} --zone=${{ secrets.GCP_INSTANCE_ZONE }} ${{ secrets.GCP_INSTANCE }} -- \
          "sudo kubectl get nodes
          "